---
- hosts: localhost
  become: true

  tasks:
  # - name: Check that you can connect (GET) to a page and it returns a status 200
  #   uri:
  #     url: https://randomuser.me

  - name: Check that a page returns a status 200 and fail if the word results is not in the page contents
    uri:
      url: https://randomuser.me/api/0.8/?results=1000
      return_content: yes
    register: this
    failed_when: "'results' not in this.content"

  - name: Execute python script to retrieve data
    script: main.py
    register: main

  - name: Debug main
    debug: var=main

  - name: Debug main.stdout as part of a string
    debug: "msg=`{{ main.stdout }}`."